import { motion } from 'framer-motion';
import { ArrowRight, CalendarDays, CircleDollarSign, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useWorkspace } from '../../app/WorkspaceProvider';
import { Avatar, Badge, Card, pageMotion } from '../../components/ui';

export function ClientsPage() {
  const { workspace } = useWorkspace(); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all');
  const clients = useMemo(() => workspace.clients.filter((client) => (!search || `${client.businessName} ${client.ownerName}`.toLowerCase().includes(search.toLowerCase())) && (status === 'all' || client.status === status)), [workspace.clients, search, status]);
  return <motion.section {...pageMotion} className="page-section"><div className="page-header"><div><h1>Client command</h1><p>Billing, proof, and every relationship after the close.</p></div><Badge tone="success">${workspace.clients.filter((client) => client.status === 'active').reduce((sum, client) => sum + client.monthlyValue, 0).toLocaleString()} MRR</Badge></div><Card className="filter-card"><div className="search-field"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search clients" /></div><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="churned">Churned</option></select></Card><div className="client-grid">{clients.map((client, index) => <motion.div key={client.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }}><Card className="client-card" data-testid={`client-card-${client.id}`}><div className="client-card-top"><Avatar initials={client.businessName.split(' ').map((word) => word[0]).join('').slice(0, 2)} tone={client.plan === 'ultraretainer' ? 'purple' : 'blue'} /><div><h3>{client.businessName}</h3><p>{client.ownerName}</p></div><Badge tone={client.subscriptionStatus === 'past_due' ? 'danger' : 'success'}>{client.subscriptionStatus?.replace('_', ' ') ?? 'active'}</Badge></div><div className="client-plan"><Badge tone={client.plan}>{client.plan === 'reviewtainer' ? 'ReviewTainer' : client.plan === 'ultraretainer' ? 'UltraRetainer' : client.plan}</Badge><strong>${client.monthlyValue}<small>/mo</small></strong></div><div className="client-meta"><span><CalendarDays size={14} />Bills {new Date(client.nextBilling).toLocaleDateString()}</span><span><CircleDollarSign size={14} />{client.contractTerm}</span></div><div className="client-card-foot"><span>Brought by {client.broughtBy.includes('terri') ? 'Terri' : 'Ashish'}</span><Link to={`/clients/${client.id}`} aria-label={`View client ${client.businessName}`}>View client <ArrowRight size={14} /></Link></div></Card></motion.div>)}</div></motion.section>;
}
